Task2
h4x4d/go_hsse_mts pull request #2
Opened 2024-10-08 22:44 UTC by h4x4d

2024-10-14 09:45 UTC, vmarunin requested changes
Не совсем понятно как запускать приложение клиент. Не нашёл вывода в консоль, который требуется в задании

Ты сделал тестами, ок. Но как их запускать? Хотелось бы в readme хоть что-то об этом.

BTW Тесты не покрывающие обработку ошибок - так себе тесты. Ну да ладно, это в следующих лекциях будет.

2024-10-14 09:45 UTC, vmarunin commented on task2/server/server/decode.go
> +			http.Error(response, err.Error(), http.StatusInternalServerError)
Ну почему 500 то? StatusInternalServerError
500-ые коды значат "на сервере что-то сломалось, но вы заходите попозже с таким же запросом, мы ответим"
400-ые коды значат "запрос плохой, повторять второй раз такой же запрос не надо"

base64 строка не по формату - 400-ые коды

2024-10-14 09:45 UTC, vmarunin commented on task2/server/server/server.go
> +	mux.HandleFunc("/version", server.VersionHandler)
В новый net/http (в 1.22) завезли методы и переменные
https://pkg.go.dev/net/http#hdr-Patterns-ServeMux

Уже не надо проверять методы в обработчиках...

2024-10-14 09:45 UTC, vmarunin commented on task2/server/server/server.go
> +	if err := server.server.ListenAndServe(); err != nil &&
А где, собственно, graceful shutdown?

2024-10-14 14:26 UTC, h4x4d commented on task2/server/server/server.go
> +	if err := server.server.ListenAndServe(); err != nil &&
добавил

2024-10-14 19:36 UTC, h4x4d commented
По поводу того, что тесты не покрывают обработку ошибок, я просто не придумал как можно ошибки триггерить, их очень много и их все не получится просто так обработать (какие-то даже не возникают почти никогда)

2024-10-18 07:14 UTC, vmarunin commented
> По поводу того, что тесты не покрывают обработку ошибок, я просто не придумал как можно ошибки триггерить, их очень много и их все не получится просто так обработать (какие-то даже не возникают почти никогда)

Никак нельзя их триггерить :) Сервер нужно писать так, чтобы он никогда не отдавал 500, или зависал, или молча закрывал TCP соединение. Но клиент должен это обрабатывать и это надо тестировать.

Противоречие разрешается тестовым сервером https://pkg.go.dev/net/http/httptest@go1.23.2#example-Server который отдаёт всякую дрянь. Вот об него и тестируют клиента, по крайней мере все эти ошибки. 

Ещё тестируют на неправильном URL (не по формату), неправильном доменном имени, неправильном IP, порту и т.д.

Зато потом клиента просто используют и даже не проверяют особенно. Иногда мокают для других компонент

Но это в следующих лекциях будет

2024-10-18 07:47 UTC, vmarunin approved these changes
Оценка 10

Но зачем канал всё равно интересно

2024-10-18 07:47 UTC, vmarunin commented on task2/server/server/server.go
> +	idleConnectionsClosed := make(chan struct{})
А этот канал зачем тут?

2024-10-29 17:59 UTC, merged